//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biz.dfch.CS.Logging.Service.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("biz.dfch.CS.Logging.Service.Core.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ARCHITECTURE_FORMATTER {
            get {
                return ResourceManager.GetString("ARCHITECTURE_FORMATTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x64.
        /// </summary>
        internal static string ARCHITECTURE_X64 {
            get {
                return ResourceManager.GetString("ARCHITECTURE_X64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x86.
        /// </summary>
        internal static string ARCHITECTURE_X86 {
            get {
                return ResourceManager.GetString("ARCHITECTURE_X86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        internal static string CMDLINE_SWITCH_H {
            get {
                return ResourceManager.GetString("CMDLINE_SWITCH_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP.
        /// </summary>
        internal static string CMDLINE_SWITCH_HELP {
            get {
                return ResourceManager.GetString("CMDLINE_SWITCH_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIPENAME.
        /// </summary>
        internal static string CMDLINE_SWITCH_PIPENAME {
            get {
                return ResourceManager.GetString("CMDLINE_SWITCH_PIPENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string CMDLINE_SWITCH_QMARK {
            get {
                return ResourceManager.GetString("CMDLINE_SWITCH_QMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d-fens biz.dfch.CS.Logging.Service {0} {1}
        ///Copyright (C) d-fens GmbH. Source code licensed under Apache 2.0 license.
        ///
        ///The biz.dfch.CS.Logging.Service is a Windows service application that executes 
        ///ScheduledJob instances defined in the Appclusive inventory.
        ///
        ///To install the service use the &apos;InstallUtil&apos; from the Microsoft .NET Framework. 
        ///Please make sure to use the version that corresponds with the .NET version this 
        ///executable was built with.
        ///
        ///Usage: biz.dfch.CS.Logging.Service [PIPENAME | HELP]        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HELP_HELP_MESSAGE {
            get {
                return ResourceManager.GetString("HELP_HELP_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d-fens biz.dfch.CS.Logging.Service {0} {1}
        ///Copyright (C) d-fens GmbH. Source code licensed under Apache 2.0 license.
        ///
        ///Starting service interactively. Press Ctrl-C to abort ....
        /// </summary>
        internal static string HELP_INTERACTIVE_MESSAGE {
            get {
                return ResourceManager.GetString("HELP_INTERACTIVE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping interactive mode..
        /// </summary>
        internal static string LoggingService_OnStartInteractive_Stopping_interactive_mode {
            get {
                return ResourceManager.GetString("LoggingService_OnStartInteractive_Stopping_interactive_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelKeyPress detected. Stopping interactive mode..
        /// </summary>
        internal static string LoggingServiceOnStartInteractiveCancelKeyPress {
            get {
                return ResourceManager.GetString("LoggingServiceOnStartInteractiveCancelKeyPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}@{1}: &apos;{2}&apos;
        ///[{3}]
        ///{4}.
        /// </summary>
        internal static string LoggingServiceOnStartInteractiveException {
            get {
                return ResourceManager.GetString("LoggingServiceOnStartInteractiveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1}.
        /// </summary>
        internal static string MESSAGE_TYPE_NAMESPACE_FULLNAME {
            get {
                return ResourceManager.GetString("MESSAGE_TYPE_NAMESPACE_FULLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d-fens biz.dfch.CS.Logging.Service {0} {1}. {2}: Environment.UserInteractive &apos;{3}&apos;.
        /// </summary>
        internal static string STARTUP_INFO {
            get {
                return ResourceManager.GetString("STARTUP_INFO", resourceCulture);
            }
        }
    }
}
